---
- name: keystore exists
  stat:
    path: "{{ elasticsearch_conf_dir }}/elasticsearch.keystore"
  register: keystore_file

- name: generate setup_keystore utils script
  ansible.builtin.template:
    src: setup_keystore.sh.j2
    dest: "/usr/local/sbin/setup_keystore.sh"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0700

- name: render password file
  ansible.builtin.template:
    src: password_file.txt.j2
    dest: /tmp/password_file.txt
    mode: 0400
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
  when: not keystore_file.stat.exists

- name: Create elastic keystore
  ansible.builtin.command: >
    su - {{ elasticsearch_user }} -c /usr/local/sbin/setup_keystore.sh
  when: not keystore_file.stat.exists

- name: Remove password file
  ansible.builtin.file:
    path: /tmp/password_file.txt
    state: absent