---
- hosts: elasticsearch
  become: yes
  remote_user: "vagrant"
  vars_files:
    - vars.yml
  tasks:
  - name: Set vm.swappiness to 10
    sysctl:
      name: vm.swappiness
      value: '10'
      sysctl_set: yes
      state: present
      reload: yes
  - name: Install Docker and Docker Compose
    apt:
      update_cache: yes
      name:
      - docker.io
      - docker-compose
    become: true
  - name: Copy docker-compose.yml file
    copy:
      src: "~/java/docker-compose.yml"
      dest: "~/docker-compose.yml"

  - name: Create containers with docker-compose
    command: docker-compose up
