---
- hosts: elasticsearch
  become: yes
  remote_user: "vagrant"
  vars_files:
    - vars.yml
  tasks:
  - name: Set vm.swappiness to 10
    sysctl:
      name: vm.swappiness
      value: '10'
      sysctl_set: yes
      state: present
      reload: yes
  - name: Install Docker 
    apt:
      update_cache: yes
      name:
      - docker.io
    become: true
  - name: Install Docker Compose
    command: curl -L "https://github.com/docker/compose/releases/download/v2.15.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
    args:
      creates: /usr/local/bin/docker-compose
    become: yes
  - name: Set permissions for Docker Compose
    command: chmod +x /usr/local/bin/docker-compose
    become: yes
  - name: Copy docker-compose.yml file
    copy:
      src: "~/java/docker-compose.yml"
      dest: "~/docker-compose.yml"
# ansible-galaxy collection install community.docker
  - name: deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: ~/
      files:
      - docker-compose.yml
